<?php
Route::get('/','HomeController@index');
Route::get('logout', 'LoginController@getLogout');
Route::get('homepage', 'HomeController@homepage');
Route::get('userProfile', 'HomeController@userProfile');
Route::get('restaurant', 'RestaurantController@index');
Route::get('index', 'HomeController@index');
Route::group(['middleware' => 'viewer'], function () {
    Route::get('login', 'LoginController@getLogin');
	Route::post('login', 'LoginController@postLogin');
	Route::get('register', 'RegisterController@create');
	// Route::post('register', 'RegisterController@store');
    Route::post('register', 'RegisterController@store');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('index', 'AdminController@index');
    Route::post('index', 'AdminController@index');
    Route::post('lock_post/{id}', 'AdminController@lock_post');
    Route::post('unlock_post/{id}', 'AdminController@unlock_post');
    Route::post('level_up/{id}', 'AdminController@level_up');
    Route::post('delete_user/{id}', 'AdminController@delete_user');
    Route::post('lock_food/{id}', 'AdminController@lock_food');
});
Route::group(['prefix' => 'shipper', 'middleware' => 'shipper'], function () {
    Route::get('index', 'ShipperController@index');
    Route::post('index', 'ShipperController@index');
    Route::get('edit_profile', 'ShipperController@edit_profile');
    Route::post('edit_profile', 'ShipperController@edit_profile');
    Route::get('update_profile/{id}', 'ShipperController@update_profile');
    Route::post('update_profile/{id}', 'ShipperController@update_profile');
    Route::get('view_receipt_detail/{id}', 'ShipperController@view_receipt_detail');
    Route::post('view_receipt_detail/{id}', 'ShipperController@view_receipt_detail');
});
Route::group(['prefix' => 'shopper', 'middleware' => 'shopper'], function () {
    Route::get('index', 'UserController@index');
    Route::post('index', 'UserController@index');
    Route::get('view_receipt/{id}', 'UserController@view_receipt');
    Route::post('view_receipt/{id}', 'UserController@view_receipt');
    Route::get('edit_order', 'UserController@edit_order');
    Route::post('edit_order', 'UserController@edit_order');
    Route::get('edit_order_food', 'UserController@edit_order_food');
    Route::post('edit_order_food', 'UserController@edit_order_food');
    Route::get('save_food/{id}', 'UserController@save_food');
    Route::post('save_food/{id}', 'UserController@save_food');
    Route::get('dis_save_food/{id}', 'UserController@dis_save_food');
    Route::post('dis_save_food/{id}', 'UserController@dis_save_food');
    Route::get('save_post/{id}', 'UserController@save_post');
    Route::post('save_post/{id}', 'UserController@save_post');
    Route::get('dis_save_post/{id}', 'UserController@dis_save_post');
    Route::post('dis_save_post/{id}', 'UserController@dis_save_post');
    Route::get('like_food/{id}', 'UserController@like_food');
    Route::post('like_food/{id}', 'UserController@like_food');
    Route::get('dis_like_food/{id}', 'UserController@dis_like_food');
    Route::post('dis_like_food/{id}', 'UserController@dis_like_food');
    Route::get('like_post/{id}', 'UserController@like_post');
    Route::post('like_post/{id}', 'UserController@like_post');
    Route::get('dis_like_post/{id}', 'UserController@dis_like_post');
    Route::post('dis_like_post/{id}', 'UserController@dis_like_post');
    Route::get('feedback', 'UserController@feedback');
    Route::post('feedback', 'UserController@feedback');
    Route::get('saved', 'UserController@saved');
    Route::post('saved', 'UserController@saved');
    Route::get('delete_receipt/{id}', 'UserController@delete_receipt');
    Route::post('delete_receipt/{id}', 'UserController@delete_receipt');
});
Route::group(['prefix' => 'post'], function () {
    Route::get('index', 'PostController@index');
    Route::get('create', 'PostController@create');
    Route::post('create', 'PostController@store');
    Route::get('edit/{id}', 'PostController@edit');
    Route::post('edit/{id}', 'PostController@update');
    Route::get('delete/{id}', 'PostController@delete');
    Route::get('view/{id}', 'PostController@view');
    Route::get('add_food/{id_food}', 'PostController@add_food');
    Route::post('add_food/{id_food}', 'PostController@add_food');
    Route::get('minus_food/{id_food}', 'PostController@minus_food');
    Route::post('minus_food/{id_food}', 'PostController@minus_food');
    Route::get('minus_food_buy/{id_food}', 'PostController@minus_food_buy');
    Route::post('minus_food_buy/{id_food}', 'PostController@minus_food_buy');
    Route::get('reset_menu', 'PostController@reset_menu');
    Route::post('reset_menu', 'PostController@reset_menu');
    Route::get('them_hang/{id_post}', 'PostController@them_hang');
    Route::post('them_hang/{id_post}', 'PostController@them_hang');
    Route::get('them_hang_buy/{id_post}', 'PostController@them_hang_buy');
    Route::post('them_hang_buy/{id_post}', 'PostController@them_hang_buy');
    Route::get('view_food/{id_food}', 'PostController@view_food');
    Route::post('view_food/{id_food}', 'PostController@view_food');
    Route::get('buy', 'PostController@buy');
    Route::post('buy', 'PostController@buy');
    Route::post('order', 'PostController@order');
    Route::get('order', 'PostController@order');
    Route::post('add_ghi_chu/{id_food}', 'PostController@add_ghi_chu');
});
Route::get('map', 'GoogleController@map');
Route::get('google_map', 'GoogleController@google_map');
Route::get('google/buy/{id}', 'GoogleController@buy');
Route::get('bai2', 'GoogleController@bai2');

Route::group(['prefix' => 'restaurant', 'middleware' => 'restaurant'], function () {
    Route::get('index', 'RestaurantController@index');
    Route::post('add_food', 'RestaurantController@add_food');
    Route::post('add_post', 'RestaurantController@add_post');
    Route::post('edit_post/{id}', 'RestaurantController@edit_post');
    Route::post('update_post/{id}', 'RestaurantController@update_post');
    Route::post('delete_post/{id}', 'RestaurantController@delete_post');
    Route::post('edit_food/{id}', 'RestaurantController@edit_food');
    Route::post('update_food/{id}', 'RestaurantController@update_food');
    Route::post('delete_food/{id}', 'RestaurantController@delete_food');
    Route::post('update_res_profile/{id}', 'RestaurantController@update_res_profile');
    Route::get('view_receipt/{id}', 'RestaurantController@view_receipt');
    Route::post('view_receipt/{id}', 'RestaurantController@view_receipt');
    Route::get('edit_profile', 'RestaurantController@edit_profile');
    Route::post('edit_profile', 'RestaurantController@edit_profile');
    Route::get('chose_shipper/{id_receipt}/{id_shipper}', 'RestaurantController@chose_shipper');
    Route::post('chose_shipper/{id_receipt}/{id_shipper}', 'RestaurantController@chose_shipper');
    Route::get('xac_nhan_receipt/{id_receipt}', 'RestaurantController@xac_nhan_receipt');
    Route::post('xac_nhan_receipt/{id_receipt}', 'RestaurantController@xac_nhan_receipt');
    Route::get('delete_receipt/{id_receipt}', 'RestaurantController@delete_receipt');
    Route::post('delete_receipt/{id_receipt}', 'RestaurantController@delete_receipt');
    Route::get('view_receipt_detail/{id}', 'RestaurantController@view_receipt_detail');
    Route::post('view_receipt_detail/{id}', 'RestaurantController@view_receipt_detail');
    Route::get('receipt_da_ship/{id}', 'RestaurantController@receipt_da_ship');
    Route::post('receipt_da_ship/{id}', 'RestaurantController@receipt_da_ship');
    Route::get('delete_receipt/{id}', 'RestaurantController@delete_receipt');
    Route::post('delete_receipt/{id}', 'RestaurantController@delete_receipt');
});

